# Generated by Django 4.1.7 on 2023-03-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='street')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='house_number')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='model')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='release date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Manufacturer'), (1, 'Reseller'), (2, 'Retailer')], default=0, verbose_name='Supplier type')),
            ],
            options={
                'verbose_name': 'Provision',
                'verbose_name_plural': 'Provisions',
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('receivables', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='receivables, RUB')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='links', to='shop.contact', verbose_name='contact')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retailers', to='shop.product', verbose_name='product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='shop.provision', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Retail',
                'verbose_name_plural': 'Retails',
            },
        ),
    ]
